### ISSUE TITLE
Minimum Xcode version in README is incorrect

### ISSUE THREAD

**Issue by shuang886** [ghall89/KeyStash#14]
The app doesn't actually build in Xcode 15.2 (and probably below) because the version number of `Package.resolved` is too high. 

<img width="469" alt="Screenshot 2024-03-24 at 7 03 51 PM" src="https://github.com/ghall89/KeyStash/assets/140762048/2178af5e-e158-41ea-81ce-6334d882a620">

I don't think this file should actually be version-controlled, but I'm not completely sure.

Builds fine in Xcode 15.3.

**Comment by ghall89** [comment]
I've added the necessary gitignore config, and to be safe updated the readme to instead say "latest version of Xcode". 👍
